(function(g){var window=this;'use strict';var C4=function(a,b){return b?a.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},D4=function(a){return g.BE(a)&&a.N("web_player_i_see_captions_3")},dUa=function(a,b){var c,d,e;
return g.B(function(f){if(1==f.i)return c=a+"|"+b,g.A(f,g.Cw(),2);if(3!=f.i){d=f.u;if(!d)throw g.aw("gct");return g.A(f,g.cF(d),3)}e=f.u;return f.return(e.get("captions",c))})},eUa=function(a,b){var c=new g.fF;
c.languageCode=a.languageCode;c.languageName=a.languageName;c.name=a.name;c.kind=a.kind;c.isDefault=!1;c.i=a.i;c.isTranslateable=a.isTranslateable;c.vssId=a.vssId;c.url=a.url;c.translationLanguage=b;return c},fUa=function(a,b,c){dUa(a,b).then(function(d){d&&c(d.trackData,new g.fF(d.metadata))})},E4=function(){this.segments=[]},gUa=function(a,b){var c=g.pc(a.segments,b);
0<=c||0>c&&1===(-c-1)%2||(c=-c-1,0<c&&1===b-a.segments[c-1]&&c<a.segments.length&&1===a.segments[c]-b?(g.cc(a.segments,c),g.cc(a.segments,c-1)):0<c&&1===b-a.segments[c-1]?a.segments[c-1]=b:c<a.segments.length&&1===a.segments[c]-b?a.segments[c]=b:(g.kc(a.segments,c,0,b),g.kc(a.segments,c+1,0,b)))},F4=function(a,b,c,d,e,f){g.H.call(this);
this.policy=a;this.player=b;this.Z=c;this.S=d;this.D=e;this.X=f;this.Y=this.player.V();this.C=new E4;this.J=-1;this.B=this.u=this.i=null;this.K=new g.K(this.WL,1E3,this);this.events=new g.BC(this);g.I(this,this.K);g.I(this,this.events);this.events.T(b,"SEEK_COMPLETE",this.DA);this.DA();this.WL()},hUa=function(a){return a.i&&a.i.D?a.i.D+a.player.kd()<a.player.getCurrentTime():!1},iUa=function(a,b){var c=g.vB(g.RB(b,a.policy,{})),d={format:"RAW",
withCredentials:!0};a.D&&(d.responseType="arraybuffer");a.B=g.Ht(c,d,3,100).then(function(e){a:{e=e.xhr;a.isDisposed();if(a.u){var f=!(a.D?e.response:e.responseText)||400<=e.status,h=g.Gpa(e);if(h){e=g.RB(a.u,a.policy,{});a.u.Dj(e,h);iUa(a,a.u);break a}f||(h=a.u.i[0].Oa,null!=a.S&&a.J!==h&&(f=a.u.i[0],a.D?a.S(e.response,1E3*(f.startTime+a.player.kd())):a.S(e.responseText,1E3*(f.startTime+a.player.kd())),a.J=h))}a.u=null;a.B=null}}).wh(function(){a.u=null;
a.B=null;a.ma()});
a.u=b;gUa(a.C,a.u.i[0].Oa)},G4=function(a,b){g.CM.call(this,b.V());
this.i=a;this.I=b;this.B=null;this.D=!1;this.J=g.DE(this.I.V())&&!this.i.isManifestless},kUa=function(a,b){var c=[],d;
for(d in a.i.i)if(a.i.i.hasOwnProperty(d)){var e=a.i.i[d];if(g.EM(e,b||null)){var f=e.info.id,h=f,l="."+f,m="";if(e=e.info.captionTrack)f=e.languageCode,h=e.displayName,l=e.vssId,m=e.kind;else{e=f;var n=g.jSa.get(e);null==n&&(n=jUa[e]||jUa[e.replace(/-/g,"_")],g.jSa.set(e,n));h=n||h}c.push(new g.fF({id:d,languageCode:f,languageName:h,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m}))}}return c},lUa=function(a,b){return null!=b&&b in a.i.i?a.i.i[b]:null},mUa=function(a,b,c){var d=
[],e;
for(e in a.i.i)if(a.i.i.hasOwnProperty(e)){var f=a.i.i[e];if(g.EM(f,c||null)){var h=f.info.captionTrack;h&&h.languageCode===b&&d.push(f)}}return d.length?d[0]:null},H4=function(a){if(!nUa.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(oUa,"#$1$1$2$2$3$3"));a=a.toLowerCase();a=parseInt(a.substr(1),16);return[a>>16,a>>8&255,a&255]},I4=function(a,b,c,d,e,f){var h={};
Object.assign(h,b);Object.assign(h,a.params);Object.assign(h,c);var l={};Object.assign(l,b.zd);a.params.zd&&Object.assign(l,a.params.zd);Object.assign(l,c.zd);h.zd=l;g.W.call(this,{G:"div",L:"caption-window",W:{id:"caption-window-"+a.id,dir:1===h.Mf?"rtl":"ltr",tabindex:"0",lang:h.lang},U:[{G:"span",L:"captions-text",W:{style:"word-wrap: normal; display: block;"}}]});this.D=[];this.xa=!1;this.u=a;this.Ba=this.Aa=null;this.playerWidth=e;this.playerHeight=f;this.J=null;this.maxWidth=.96*e;this.Sa=.96*
f;this.i=h;this.wb=c;this.Ja=b;this.C=this.Fa("captions-text");this.ob=""!==this.C.style.getPropertyValue("box-decoration-break")||""!==this.C.style.getPropertyValue("-webkit-box-decoration-break");this.Ka=d/360*16;this.type=0;this.Xa=this.Ka*pUa(l);a=new g.Cx(this.element,!0);g.I(this,a);a.subscribe("dragstart",this.CQ,this);a.subscribe("dragmove",this.BQ,this);a.subscribe("dragend",this.AQ,this);this.fb=this.Za=0;b="";this.i.windowOpacity&&(a=H4(this.i.windowColor),b="rgba("+a[0]+","+a[1]+","+a[2]+
","+this.i.windowOpacity+")");a={"background-color":b,display:!1===this.i.isVisible?"none":"","text-align":qUa[this.i.textAlign]};this.ob&&(a["border-radius"]=b?this.Xa/8+"px":"");if(this.B=2===this.u.params.Mf||3===this.u.params.Mf)b=this.element,c="vertical-rl",1===this.i.dH&&(c="vertical-lr"),g.Kc&&(c="vertical-lr"===c?"tb-lr":"tb-rl"),g.Em(b,"-o-writing-mode",c),g.Em(b,"-webkit-writing-mode",c),g.Em(b,"writing-mode",c),g.Em(b,"text-orientation","upright"),g.M(b,"ytp-vertical-caption"),3===this.u.params.Mf&&
(g.Em(b,"text-orientation",""),g.Em(b,"transform","rotate(180deg)"));g.Em(this.element,a);switch(this.i.wi){case 0:case 1:case 2:g.M(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.M(this.element,"ytp-caption-window-bottom")}},pUa=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0===a.offset||2===a.offset)b*=.8;return b},rUa=function(a,b){var c={},d=b.background?b.background:a.i.zd.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.i.zd.backgroundOpacity;d=H4(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.ob&&(c["box-decoration-break"]="clone",c["border-radius"]=a.Xa/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.Ka*pUa(b)+"px";d=1;e=b.color||a.i.zd.color;if(b.color||null!=b.textOpacity)e=H4(e),d=null==b.textOpacity?a.i.zd.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",c.color=
e,c.fill=e;var f=b.charEdgeStyle;0===f&&(f=void 0);if(f){e="rgba(34, 34, 34, "+d+")";var h="rgba(204, 204, 204, "+d+")";b.xD&&(h=e=b.xD);var l=a.Ka/16/2,m=Math.max(l,1),n=Math.max(2*l,1),p=Math.max(3*l,1),r=Math.max(5*l,1);d=[];switch(f){case 4:for(;p<=r;p+=l)d.push(n+"px "+n+"px "+p+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=p;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+h);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(p=0;5>p;p++)d.push("0 0 "+n+"px "+
e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.pu()?'"Carrois Gothic SC", sans-serif-smallcaps':
'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.i.zd.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7===b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.Fj&&(c["font-style"]="italic");b.underline&&(c["text-decoration"]="underline");
b.jT&&(c.visibility="hidden");1===b.nL&&a.B&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.HE||g.Zv,3===a.u.params.Mf?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(1===b.Wj||2===b.Wj||3===b.Wj||4===b.Wj||5===b.Wj)if(g.HE)c["font-weight"]="bold";else switch(c["text-emphasis-style"]="filled circle",c["text-emphasis-color"]="currentcolor",c["webkit-text-emphasis"]="filled circle",b.Wj){case 4:case 3:c["text-emphasis-position"]="under left";
c["webkit-text-emphasis-position"]="under left";break;case 5:case 2:c["text-emphasis-position"]="over right",c["webkit-text-emphasis-position"]="over right"}return c},sUa=function(a){a.J=g.hh("SPAN");
g.Em(a.J,{display:"block"});g.M(a.J,"caption-visual-line");a.C.appendChild(a.J)},tUa=function(a,b){var c=g.hh("SPAN");
g.Em(c,{display:"inline-block","white-space":"pre-wrap"});g.Em(c,rUa(a,b));c.classList.add("ytp-caption-segment");a.J.appendChild(c);c.previousElementSibling&&(g.Em(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.Em(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},uUa=function(a,b,c){a.xa=a.xa||!!c;
var d={};Object.assign(d,a.i.zd);Object.assign(d,c||b.i);Object.assign(d,a.wb.zd);(c=!a.J)&&sUa(a);for(var e=a.Aa&&a.Ba&&g.Ze(d,a.Ba)?a.Aa:tUa(a,d),f="string"===typeof b.text,h=f?b.text.split("\n"):[b.text],l=0;l<h.length;l++){var m=0<l||!b.append,n=h[l];m&&!c?(sUa(a),e=tUa(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.ih(n):n),f||"RUBY"!==n.tagName||4!==n.childElementCount||g.HE||!g.Hm(n.children[2],"text-emphasis")||(m=a.B?"padding-right":"padding-top",g.Hm(n.children[2],"text-emphasis-position")&&(m=
a.B?"padding-left":"padding-bottom"),g.ch?g.Em(e,m,"1em"):g.Em(e,m,"0.5em")))}a.Ba=d;a.Aa=e;a.D.push(b)},J4=function(a,b,c,d){g.CM.call(this,a);
this.videoData=b;this.audioTrack=c;this.Ua=d;this.C=b.HE},K4=function(a,b,c,d,e,f,h){I4.call(this,a,b,c,d,e,f,h);
this.type=1},L4=function(a,b,c,d,e,f,h){I4.call(this,a,b,c,d,e,f,h);
this.type=2;this.K=[];this.X=this.S=this.La=0;this.Z=NaN;this.kb=0;this.Bb=null;this.Va=new g.K(this.jW,433,this);g.M(this.element,"ytp-caption-window-rollup");g.I(this,this.Va);g.Em(this.element,"overflow","hidden")},vUa=function(a,b){if(!b)return"";
a.B&&1!==a.u.params.dH&&(b*=-1);return"translate"+(a.B?"X":"Y")+"("+b+"px)"},wUa=function(a){a.K=Array.from(document.getElementsByClassName("caption-visual-line"));
for(var b=a.u.params.Im,c=0,d=0,e=a.K.length-1;c<b&&-1<e;){var f=a.K[e];d+=a.B?f.offsetWidth:f.offsetHeight;c++;e--}a.K.length<b&&(d*=b/a.K.length);a.S=d;b=Math;c=b.max;isNaN(a.Z)&&((d=a.i.qn)?(e=g.hh("SPAN"),g.oh(e,"\u2013".repeat(d)),g.Em(e,rUa(a,a.i.zd)),a.C.appendChild(e),a.Z=e.offsetWidth,a.C.removeChild(e)):a.Z=0);d=a.C;a.X=c.call(b,a.Z,a.kb,(a.B?d.offsetHeight:d.offsetWidth)+1)},xUa=function(a,b){wUa(a);
var c=a.K.reduce(function(e,f){return(a.B?f.offsetWidth:f.offsetHeight)+e},0);
c=a.S-c;if(c!==a.La){var d=0<c&&0===a.La;b||isNaN(c)||d||(g.M(a.element,"ytp-rollup-mode"),g.lr(a.Va));g.Em(a.C,"transform",vUa(a,c));a.La=c}wUa(a)},M4=function(a,b,c,d,e,f,h){f=void 0===f?!1:f;
h=void 0===h?null:h;g.Ny.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.append=f;this.i=h},N4=function(a,b,c,d,e){g.Ny.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.i=[]},yUa=function(a){var b="_"+O4++;
return new N4(0,0x8000000000000,0,b,a)},AUa=function(a,b,c,d,e,f,h){var l=f[0],m=h[l.getAttribute("p")];
if(1===m.pe){var n=f[1],p=f[2];f=f[3];l.getAttribute("t");n.getAttribute("t");p.getAttribute("t");f.getAttribute("t");l.getAttribute("p");n.getAttribute("p");f.getAttribute("p");h=h[p.getAttribute("p")];l=zUa(l.textContent,n.textContent,p.textContent,f.textContent,h);return new M4(a,b,e,c,l,d,m)}switch(m.pe){case 9:case 10:m.Wj=1;break;case 11:m.Wj=2;break;case 12:m.Wj=3;break;case 13:m.Wj=4;break;case 14:m.Wj=5}return new M4(a,b,e,c,l.textContent||"",d,m)},zUa=function(a,b,c,d,e){var f=g.pu(),h=
f?g.hh("DIV"):g.hh("RUBY"),l=g.hh("SPAN");
l.textContent=a;h.appendChild(l);a=f?g.hh("DIV"):g.hh("RP");a.textContent=b;h.appendChild(a);b=f?g.hh("DIV"):g.hh("RT");b.textContent=c;h.appendChild(b);c=e.pe;if(10===c||11===c||12===c||13===c||14===c)if(g.Em(b,"text-emphasis-style","filled circle"),g.Em(b,"text-emphasis-color","currentcolor"),g.Em(b,"webkit-text-emphasis","filled circle"),11===e.pe||13===e.pe)g.Em(b,"webkit-text-emphasis-position","under left"),g.Em(b,"text-emphasis-position","under left");c=!0;if(4===e.pe||7===e.pe||12===e.pe||
14===e.pe)g.Em(h,"ruby-position","over"),g.Em(h,"-webkit-ruby-position","before");else if(5===e.pe||6===e.pe||11===e.pe||13===e.pe)g.Em(h,"ruby-position","under"),g.Em(h,"-webkit-ruby-position","after"),c=!1;e=f?g.hh("DIV"):g.hh("RP");e.textContent=d;h.appendChild(e);f&&(d=c,g.Em(h,{display:"inline-block",position:"relative"}),f=h.firstElementChild.nextElementSibling,g.Em(f,"display","none"),f=f.nextElementSibling,g.Em(f,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.Em(h.lastElementChild,"display","none"),d?(g.Em(h,"padding-top","0.6em"),g.Em(f,"top","0")):(g.Em(h,"padding-bottom","0.6em"),g.Em(f,"bottom","0")));return h},P4=function(){g.H.apply(this,arguments)},Q4=function(a){P4.call(this);
this.C=a;this.pens={};this.S={};this.X={};this.D="_"+O4++;this.K={};this.B=this.i=null;this.J=!0},R4=function(a,b){a=a.getAttribute(b);
if(null!=a)return Number(a)},S4=function(a,b){a=a.getAttribute(b);
if(null!=a)return"1"===a},T4=function(a,b){a=R4(a,b);
return void 0!==a?a:null},V4=function(a,b){a=a.getAttribute(b);
if(null!=a)return U4.test(a),a},BUa=function(a,b){var c={},d=b.getAttribute("ws");
Object.assign(c,d?a.X[d]:a.C);a=T4(b,"mh");null!=a&&(c.kt=a);a=T4(b,"ju");null!=a&&(c.textAlign=a);a=T4(b,"pd");null!=a&&(c.Mf=a);a=T4(b,"sd");null!=a&&(c.dH=a);a=V4(b,"wfc");null!=a&&(c.windowColor=a);b=R4(b,"wfo");void 0!==b&&(c.windowOpacity=b/255);return c},CUa=function(a,b){var c={},d=b.getAttribute("wp");
d&&Object.assign(c,a.S[d]);a=T4(b,"ap");null!=a&&(c.wi=a);a=R4(b,"cc");null!=a&&(c.qn=a);a=R4(b,"ah");null!=a&&(c.jh=a);a=R4(b,"rc");null!=a&&(c.Im=a);b=R4(b,"av");null!=b&&(c.Xj=b);return c},DUa=function(a,b,c,d){var e={};
Object.assign(e,CUa(a,b));Object.assign(e,BUa(a,b));d?g.Ze(e,a.C)?(d=a.D,e=a.C):d="_"+O4++:d=b.getAttribute("id")||"_"+O4++;a=R4(b,"t")+c;b=R4(b,"d")||0x8000000000000;if(2===e.Mf||3===e.Mf)c=e.Im,e.Im=e.qn,e.qn=c;return new N4(a,b,0,d,e)},W4=function(a){P4.call(this);
this.J=a;this.i=new Map;this.C=new Map;this.D=new Map;this.B=new Map},X4=function(a){a=g.xg(Math.round(a),0,16777215).toString(16).toUpperCase();
return"#000000".substr(0,7-a.length)+a},EUa=function(a,b,c,d,e){0===d&&(d=0x8000000000000);
var f={};b.wpWinPosId&&Object.assign(f,a.C.get(b.wpWinPosId));b.wsWinStyleId&&Object.assign(f,a.D.get(b.wsWinStyleId));a=b.rcRowCount;void 0!==a&&(f.Im=a);b=b.ccColCount;void 0!==b&&(f.qn=b);if(2===f.Mf||3===f.Mf)b=f.Im,f.Im=f.qn,f.qn=b;return new N4(c,d,0,e,f)},Z4=function(){this.B=this.time=this.mode=this.u=0;
this.C=new Y4(this);this.D=new Y4(this);this.i=[];this.clear()},GUa=function(a,b,c){if(255===a&&255===b||!a&&!b)return{vp:a,
fn:b,result:0};a=FUa[a];b=FUa[b];if(a&128){var d;if(d=!(b&128))d=b,d=c.isValid()&&c.fn===d;if(d)return{vp:a,fn:b,result:1}}else if(b&128&&1<=a&&31>=a)return{vp:a,fn:b,result:2};return{vp:a,fn:b,result:3}},IUa=function(a,b,c,d){255===b&&255===c||!b&&!c?(45===++a.B&&a.reset(),a.C.u.clear(),a.D.u.clear()):(a.B=0,HUa(a.C,b,c,d))},JUa=function(a,b){a.i.sort(function(e,f){var h=e.time-f.time;
return 0===h?e.order-f.order:h});
for(var c=g.q(a.i),d=c.next();!d.done;d=c.next())d=d.value,a.time=d.time,0===d.type?IUa(a,d.OJ,d.PJ,b):1===d.type&&a.u&496&&HUa(a.D,d.OJ,d.PJ,b);a.i.length=0},$4=function(){this.type=0},a5=function(){this.state=this.fn=this.vp=0},KUa=function(){this.timestamp=this.i=0},b5=function(a){this.D=a;
this.B=[];this.i=this.u=this.row=0;this.style=new $4;for(a=this.C=0;15>=a;a++){this.B[a]=[];for(var b=0;32>=b;b++)this.B[a][b]=new KUa}},c5=function(a,b){if(3===a.style.type){for(var c=0,d=0,e=a.D.time+0,f="",h="",l=e,m=1;15>=m;++m){for(var n=!1,p=d?d:1;32>=p;++p){var r=a.B[m][p];
if(0!==r.i){0===c&&(c=m,d=p);n=String.fromCharCode(r.i);var t=r.timestamp;t<e&&(e=t);r.timestamp=l;h&&(f+=h,h="");f+=n;n=!0}if((0===r.i||32===p)&&n){h="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.D(c,d,e,l,f)}else for(d=c=0,f=e=a.D.time+0,h=1;15>=h;++h)for(l="",m=1;32>=m;++m)if(p=a.B[h][m],r=p.i,0!==r&&(0===c&&(c=h,d=m),n=String.fromCharCode(r),t=p.timestamp,t<=e&&(e=t),l+=n,p.reset()),32===m||0===r)l&&b.D(c,d,e,f,l),e=f,l="",d=c=0},PUa=function(a,b){switch(a){case 0:return LUa[(b&127)-32];
case 1:return MUa[b&15];case 2:return NUa[b&31];case 3:return OUa[b&31]}return 0},d5=function(a){return a.B[a.row][a.u]},e5=function(a,b,c){2<=b&&1<a.u&&(--a.u,d5(a).i=0);
var d=d5(a);d.timestamp=a.D.time+0;d.i=PUa(b,c);32>a.u&&a.u++},QUa=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++){var h=a.B[b+e][f],l=a.B[c+e][f];
h.i=l.i;h.timestamp=l.timestamp}},f5=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.B[b+d][e].reset()},g5=function(a){a.row=0<a.i?a.i:1;
a.u=1;f5(a,0,15)},h5=function(a){this.B=a;
this.D=0;this.style=new $4;this.J=new b5(this.B);this.K=new b5(this.B);this.text=new b5(this.B);this.u=this.J;this.C=this.K;this.i=this.u},i5=function(a,b,c){var d=a.u,e=!1;
switch(a.style.get()){case 4:case 1:case 2:4===a.style.get()&&0<d.i||(c5(d,c),g5(a.u),g5(a.C),d.row=15,d.i=b,e=!0)}a.style.set(3);a.i=d;a.i.style=a.style;a.B.mode=1<<d.C;e?d.u=1:d.i!==b&&(d.i>b?(c5(d,c),f5(d,d.row-d.i,b)):d.row<b&&(b=d.i),d.i=b)},RUa=function(a){a.style.set(1);
a.i=a.C;a.i.i=0;a.i.style=a.style;a.B.mode=1<<a.i.C},SUa=function(a){a.style.set(4);
a.i=a.text;a.i.style=a.style;a.B.mode=1<<a.i.C},Y4=function(a){this.i=a;
this.D=0;this.B=new h5(this.i);this.J=new h5(this.i);this.u=new a5;this.C=this.B},HUa=function(a,b,c,d){a.u.update();
b=GUa(b,c,a.u);switch(b.result){case 0:return;case 1:case 2:return}var e=b.vp;c=b.fn;if(32<=e||!e)a.i.mode&a.i.u&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.C.i,b&96&&e5(a,0,b),c&96&&e5(a,0,c),0!==b&&0!==c&&3===a.style.type&&c5(a,d));else if(e&16)a:if(!a.u.matches(e,c)&&(b=a.u,b.vp=e,b.fn=c,b.state=2,b=e&8?a.J:a.B,a.C=b,a.i.mode=1<<(a.D<<2)+(b.D<<1)+(4===b.style.type?1:0),(a.i.mode|1<<(a.D<<2)+(b.D<<1)+(4!==b.style.type?1:0))&a.i.u))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];
a=c&16?4*((c&14)>>1):0;c=b.i;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!==c.row){if(d<c.i&&(d=c.i,d===c.row))break;var f=1+c.row-c.i,h=1+d-c.i;QUa(c,h,f,c.i);b=f;e=c.i;h<f?(f=h+e-f,0<f&&(b+=f,e-=f)):(f=f+e-h,0<f&&(e-=f));f5(c,b,e)}}c.row=d;c.u=a+1}else switch(e&7){case 1:switch(c&112){case 32:e5(b.i,0,32);break a;case 48:57===c?(d=b.i,d5(d).i=0,32>d.u&&d.u++):e5(b.i,1,c&15)}break;case 2:c&32&&e5(b.i,2,c&31);break;case 3:c&32&&e5(b.i,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:RUa(b);
break;case 33:d=b.i;1<d.u&&(--d.u,d5(d).i=0);break;case 36:d=b.i;b=d5(d);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(d.B[a][c]===b){for(;32>=c;c++)d.B[a][c].reset();break}break;case 37:i5(b,2,d);break;case 38:i5(b,3,d);break;case 39:i5(b,4,d);break;case 40:e5(b.i,0,32);break;case 41:b.style.set(2);b.i=b.u;b.i.i=0;b.i.style=b.style;b.B.mode=1<<b.i.C;break;case 42:d=b.text;d.i=15;d.style.set(4);g5(d);SUa(b);break;case 43:SUa(b);break;case 44:a=b.u;switch(b.style.get()){case 1:case 2:case 3:c5(a,d)}f5(a,
0,15);break;case 45:b:{a=b.i;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.u=1;break b}case 3:}2>a.i&&(a.i=2,a.row<a.i&&(a.row=a.i));b=a.row-a.i+1;c5(a,d);QUa(a,b,b+1,a.i-1);f5(a,a.row,1)}break;case 46:f5(b.C,0,15);break;case 47:c5(b.u,d),b.C.updateTime(b.B.time+0),d=b.C,b.C=b.u,b.u=d,RUa(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.i,32<(d.u+=c&3)&&(d.u=32)}}},TUa=function(){},j5=function(a,b,c){this.trackData=a;
this.K=c;this.version=this.J=this.C=this.i=0;this.u=new DataView(this.trackData);this.B=[]},k5=function(a){var b=a.i;
a.i+=1;return a.u.getUint8(b)},l5=function(a){var b=a.i;
a.i+=4;return a.u.getUint32(b)},m5=function(a,b){P4.call(this);
this.B=a;this.C=b;this.track="CC3"===this.C.languageName?4:0;this.i=new Z4;this.i.u=1<<this.track},n5=function(a){if("string"===typeof a)return!1;
a=new j5(a,8,0);return UUa(a)},UUa=function(a){if(!(a.i<a.u.byteLength)||1380139777!==l5(a))return!1;
a.version=k5(a);if(1<a.version)return!1;k5(a);k5(a);k5(a);return!0},o5=function(){P4.call(this)},VUa=function(a,b,c,d,e,f,h,l,m){switch(h.tagName){case "b":l.bold=!0;
break;case "i":l.Fj=!0;break;case "u":l.underline=!0}for(var n=0;n<h.childNodes.length;n++){var p=h.childNodes[n];if(3===p.nodeType)p=new M4(b,c,d,e.id,p.nodeValue,f||0<n,g.We(l)?void 0:l),m.push(p),e.i.push(p);else{var r={};Object.assign(r,l);VUa(a,b,c,d,e,!0,p,r,m)}}},p5=function(a){var b=a.split(":");
a=0;b=g.q(b);for(var c=b.next();!c.done;c=b.next())a=60*a+Number(c.value);return 1E3*a},WUa=function(a,b,c,d){d=Object.assign({kt:0},d);
return new N4(a,b,c,"_"+O4++,d)},q5=function(a,b){g.H.call(this);
this.I=a;this.Y=b;this.i=null;this.u=this.I.Js()},bVa=function(a,b,c,d,e){d=d||0;
e=e||0;if(a.Y.N("enable_h5_ssdai_caption")&&b){var f=e,h=XUa(a,b,d),l=[];try{for(var m=g.q(h),n=m.next();!n.done;n=m.next()){var p=n.value,r=p.trackData,t=p.UG;l="string"!==typeof r?l.concat(YUa(a,c,r,t,f)):"WEBVTT"===r.substring(0,6)?l.concat(ZUa(a,r,t)):l.concat($Ua(a,c,r,t))}var v=l}catch(x){g.Wx(x),a.clear(),v=[]}if(0!==v.length)return v}b=aVa(b);if(!b)return[];try{return"string"!==typeof b?YUa(a,c,b,d,e):"WEBVTT"===b.substring(0,6)?ZUa(a,b,d):$Ua(a,c,b,d)}catch(x){return g.Wx(x),a.clear(),[]}},
aVa=function(a){if("string"===typeof a||n5(a))return a;
var b=new DataView(a);if(8>=b.byteLength||1718909296!==b.getUint32(4))return"";b=g.XA(b,0,1835295092);if(!b||!b.size)return"";a=new Uint8Array(a,b.dataOffset,b.size-(b.dataOffset-b.offset));return g.KA(a)},XUa=function(a,b,c){if("string"===typeof b||n5(b))return[{trackData:b,
UG:c}];var d=new DataView(b);if(8>=d.byteLength||1718909296!==d.getUint32(4))return[];var e=g.voa(d);if(a.u&&e){var f=g.ooa(e);e=e.i;f&&e&&a.u.Nx(e,f)}f=g.fB(d,1835295092);if(!f||!f.length||!f[0].size)return[];a=[];f=g.q(f.entries());for(e=f.next();!e.done;e=f.next()){var h=g.q(e.value);e=h.next().value;h=h.next().value;h=new Uint8Array(b,h.dataOffset,h.size-(h.dataOffset-h.offset));h=g.KA(h);a.push({trackData:h,UG:c+1E3*e})}cVa(d,a,c);return a=a.filter(function(l){return!!l.trackData})},cVa=function(a,
b,c){var d=g.XA(a,0,1836476516),e=9E4;
d&&(e=g.YA(d)||9E4);d=0;var f=g.fB(a,1836019558);f=g.q(f.entries());for(var h=f.next();!h.done;h=f.next()){var l=g.q(h.value);h=l.next().value;l=l.next().value;h<b.length&&(l=g.XA(a,l.dataOffset,1953653094))&&(l=g.XA(a,l.dataOffset,1952867444))&&(l=g.dB(l)/e*1E3,0===h&&(d=l),b[h].UG=l-d+c||c*h*1E3)}},YUa=function(a,b,c,d,e){if(!n5(c))throw Error("Invalid binary caption track data");
a.i||(a.i=new m5(e,b));return a.i.u(c,d)},ZUa=function(a,b,c){a.i||(a.i=new o5);
a=a.i.u(b,c);.01>Math.random()&&g.Xx(Error("Deprecated subtitles format in web player: WebVTT"));return a},$Ua=function(a,b,c,d){if("{"===c[0])try{return a.i||(a.i=new W4(dVa(b))),a.i.u(c,d)}catch(f){return g.Wx(f),[]}var e=g.Y1(c);
if(!e||!e.firstChild)throw a=Error("Invalid caption track data"),a.params=c,a;if("timedtext"===e.firstChild.tagName){if(3===Number(e.firstChild.getAttribute("format")))return a.i||(a.i=new Q4(dVa(b),a.Y)),a.i.u(e,d);a=Error("Unsupported subtitles format in web player (Format2)");a.params=c;throw a;}if("transcript"===e.firstChild.tagName)throw a=Error("Unsupported subtitles format in web player (Format1)"),a.params=c,a;a=Error("Invalid caption track data");a.params=c;throw a;},dVa=function(a){var b=
{};
if(a=g.iF(a))b.lang=a,g.DQa.test(a)&&(b.Mf=1);return b},t5=function(a){g.zM.call(this,a);
var b=this;this.I=a;this.Y=this.I.V();this.videoData=this.I.getVideoData();this.qb=this.I.bb();this.C={zd:{}};this.D={zd:{}};this.xa=[];this.S={};this.Ka={};this.Z=!1;this.Bb=g.hG(this.videoData);this.Xa=g.Hya(this.videoData,this.I);this.ob=!!this.videoData.captionTracks.length;this.wb=!!this.videoData.jc;this.La="3"===this.Y.controlsType;this.u=this.J=this.K=this.Ja=this.Za=null;this.Va=new q5(this.I,this.Y);this.i=null;this.oa=new g.BC(this);this.Sa=new g.W({G:"div",L:"ytp-caption-window-container",
W:{id:"ytp-caption-window-container"}});var c=null,d=g.$r("yt-html5-player-modules::subtitlesModuleData");d&&(c=new g.Or(d));this.storage=c;c=a.qd();this.fb=!(null===c||void 0===c||!c.Gx());this.B=eVa(this);this.X=!this.B&&this.La&&this.fb&&this.Xa;g.I(this,this.Va);this.B?this.Ba=this.Aa=null:(this.Aa=new g.jr(this.uH,void 0,this),g.I(this,this.Aa),this.Ba=new g.K(this.BX,2E3,this),g.I(this,this.Ba));g.I(this,this.oa);this.Y.N("caption_window_container_killswitch")||g.lM(this.player,this.Sa.element,
4);g.I(this,this.Sa);this.B||this.oa.T(a,"resize",this.wH);(this.kb=!g.rx()&&!this.I.isFullscreen()&&!this.B&&!this.X&&!this.Y.N("switch_captions_to_track_tag_when_fullscreen_api_unavailable_killswitch"))&&this.oa.T(a,"resize",this.rV);this.oa.T(a,"onPlaybackAudioChange",this.BU);this.oa.T(a,g.Py("captions"),function(e){b.onCueRangeEnter(e)});
this.oa.T(a,g.Qy("captions"),function(e){b.onCueRangeExit(e)});
r5(this,s5(this)||{})},hVa=function(a){if(1===a.Y.Va||1===a.videoData.Ou||"alwayson"===g.SF(a.videoData,"yt:cc"))return!0;
if(a.videoData.captionTracks.length)var b=a.player.getAudioTrack().u;var c=a.Y;if(g.BE(c)&&c.N("web_player_prioritize_caption_visibility_on"))return"ON"===b||"on"===g.SF(a.videoData,"yt:cc");if(2===a.Y.Va){var d;g.FE(a.Y)?d=fVa(a):d=gVa(a,"module-enabled");if(null!=d)return!!d}c=C4(a.player.getAudioTrack(),D4(a.Y));d=g.SF(a.videoData,"yt:cc");if(void 0===u5(a)){if("CAPTIONS_INITIAL_STATE_ON_RECOMMENDED"===c)return d?"on"===d:!0;if("CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED"===c)return"on"===d}else return"on"===
d;return"ON"===b||"on"===g.SF(a.videoData,"yt:cc")},v5=function(a,b){if(a.i&&(void 0===b||!b)||!a.videoData.captionTracks.length)return!1;
a=a.player.getAudioTrack();return!!a.i||"FORCED_ON"===a.u},u5=function(a){var b=void 0,c=g.Dv(g.Cv.getInstance(),65);
if(g.FE(a.Y)&&null!=c){if(null!=fVa(a))return!1;b=!c}return b},iVa=function(a){var b;
a.Bb?b=new J4(a.Y,a.videoData,a.player.getAudioTrack(),a.player):a.Xa?b=new G4(a.videoData.i,a.player):a.ob?b=new g.DM(a.Y,a.videoData,a.player.getAudioTrack()):b=new g.FM(a.Y,a.videoData.jc,a.videoData.videoId,g.pta(a.videoData),a.videoData.rj);return b},x5=function(a,b){if(a.u){if(a.J&&a.J.C)return a.J.C;
b||(b=a.wb?!1:a.ob?!1:!0);b=g.AM(a.u.u,b);for(var c=[a.videoData.captionsLanguagePreference,a.Y.captionsLanguagePreference,g.SF(a.videoData,"yt:cc_default_lang")],d=0;d<c.length;d++)for(var e=0;e<b.length;e++)if(g.iF(b[e])===c[d])return b[e];return a.J&&a.J.B?a.J.B:(c=b.find(function(f){return f.isDefault}))?c:b[0]||w5(a)}return null},w5=function(a){return a.J&&a.J.i},y5=function(a){var b=w5(a);
return!!b&&a.i===b},jVa=function(a){var b=C4(a.player.getAudioTrack(),D4(a.Y)),c;
"CAPTIONS_INITIAL_STATE_UNKNOWN"===b?u5(a)||a.Z||hVa(a)?c=x5(a,a.Z):v5(a)&&(c=w5(a)):"CAPTIONS_INITIAL_STATE_ON_REQUIRED"===b?c=x5(a,a.Z):"CAPTIONS_INITIAL_STATE_OFF_REQUIRED"===b&&v5(a)&&(c=w5(a));if(a.B||a.X){var d=g.AM(a.u.u,!0);b=[];for(var e=0;e<d.length;e++){var f=d[e],h=g.hh("TRACK");h.setAttribute("kind","subtitles");h.setAttribute("label",g.gF(f));h.setAttribute("srclang",g.iF(f));h.setAttribute("id",f.toString());a.X||h.setAttribute("src",a.u.Tp(f,"vtt"));f===c&&h.setAttribute("default",
"1");b.push(h)}c=a.I.qd();c.Su(b);c=c.Ee();a.fb&&a.oa.T(c.textTracks,"change",a.TW)}else!a.i&&c&&z5(a,c),a.player.Pa("onCaptionsTrackListChanged"),a.player.Pa("onApiChange")},kVa=function(a,b){var c=a.I.qd().Ee().textTracks;
a=a.i.toString();for(var d=0;d<c.length;d++){var e=c[d];e.id===a&&(b?"showing"!==e.mode&&(e.mode="showing"):"showing"===e.mode&&(e.mode="disabled"))}},z5=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.Z=c,a.Z&&(g.FE(a.Y)?A5(a,!!b):B5(a,"module-enabled",!!b)));a.i=b;v5(a)&&(a.i=w5(a));a.load()},lVa=function(a,b){a.Y.N("caption_window_container_killswitch")?g.lM(a.player,b,4):a.Sa.element.appendChild(b)},mVa=function(a,b){var c=a.qb.getVideoContentRect(!0).height;
if(!c)return null;var d=a.i?g.iF(a.i):null;d&&g.DQa.test(d)&&(b.params.Mf=1);d=a.qb.getPlayerSize();switch(null!=b.params.kt?b.params.kt:1<b.i.length?1:0){case 1:return new K4(b,a.C,a.D,c,d.width,d.height,a.Y.experiments);case 2:return new L4(b,a.C,a.D,c,d.width,d.height,a.Y.experiments);default:return new I4(b,a.C,a.D,c,d.width,d.height,a.Y.experiments)}},r5=function(a,b,c){c=void 0===c?!1:c;
var d=C5.zd;a.C={};Object.assign(a.C,C5);a.C.zd={};Object.assign(a.C.zd,d);a.D={zd:{}};var e=b.backgroundOverride?a.D:a.C,f=b.background||d.background;U4.test(f);e.zd.background=f;e=b.colorOverride?a.D:a.C;f=b.color||d.color;U4.test(f);e.zd.color=f;e=b.windowColorOverride?a.D:a.C;f=b.windowColor||C5.windowColor;U4.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.D:a.C;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.zd.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.D:a.C;f=b.fontSizeIncrement;
null==f&&(f=d.fontSizeIncrement);e.zd.fontSizeIncrement=f;f=b.fontStyleOverride?a.D:a.C;e=b.fontStyle;null==e&&(e=d.bold&&d.Fj?3:d.bold?1:d.Fj?2:0);f=f.zd;switch(e){case 1:f.bold=!0;delete f.Fj;break;case 2:delete f.bold;f.Fj=!0;break;case 3:f.bold=!0;f.Fj=!0;break;default:delete f.bold,delete f.Fj}e=b.textOpacityOverride?a.D:a.C;f=b.textOpacity;null==f&&(f=d.textOpacity);e.zd.textOpacity=f;e=b.windowOpacityOverride?a.D:a.C;f=b.windowOpacity;null==f&&(f=C5.windowOpacity);e.windowOpacity=f;e=b.charEdgeStyleOverride?
a.D:a.C;f=b.charEdgeStyle;null==f&&(f=d.charEdgeStyle);e.zd.charEdgeStyle=f;e=b.fontFamilyOverride?a.D:a.C;f=b.fontFamily;null==f&&(f=d.fontFamily);e.zd.fontFamily=f;a.loaded&&a.wH();c&&(a.Y.N("web_player_local_storage_for_captions_setting_killswitch")?B5(a,"display-settings",b):g.ky("yt-player-caption-display-settings",b,2592E3))},D5=function(a,b,c){b&&!a.K?(b=yUa({Mf:0,
lang:"en"}),a.K=[b,new M4(b.start,b.end-b.start,0,b.id,null!==c&&void 0!==c?c:"Captions look like this")],a.player.Gd(a.K)):!b&&a.K&&(nVa(a,a.K),a.K=null)},nVa=function(a,b){a.player.Kf(b);
g.uc(b,function(c){g.dc(this.xa,c)},a);
g.kr(a.Aa)},gVa=function(a,b){if(!a.storage)return null;
try{var c=a.storage.get(b)}catch(d){a.storage.remove(b)}return c},B5=function(a,b,c){if(a.storage)try{a.storage.set(b,c)}catch(d){}},A5=function(a,b){a.I.isInline()||g.ky("yt-player-sticky-caption",b,2592E3)},fVa=function(a){if(!a.I.isInline())return g.ly("yt-player-sticky-caption")},s5=function(a){return a.Y.N("web_player_local_storage_for_captions_setting_killswitch")?gVa(a,"display-settings"):g.ly("yt-player-caption-display-settings")},eVa=function(a){var b=a.I.qd();
b=!(null===b||void 0===b||!b.Fx());return a.La&&b&&!a.Xa};
g.zS.prototype.Jv=g.ca(33,function(a){var b=2;this.Aa.has(a)?b=0:g.wEa(this,a)&&(b=1);return b});
g.fV.prototype.Jv=g.ca(32,function(a){return this.wd.Jv(a)});
g.zS.prototype.Nx=g.ca(31,function(a,b){this.La.set(a,b)});
g.fV.prototype.Nx=g.ca(30,function(a,b){this.wd.Nx(a,b)});
g.RM.prototype.Zr=g.ca(29,function(){this.ma();for(var a=g.Vg(document,"track",void 0,this.i),b=0;b<a.length;b++)g.lh(a[b])});
g.gS.prototype.Zr=g.ca(28,function(){this.ra.Zr()});
g.RM.prototype.Gx=g.ca(27,function(){return!(!this.i.textTracks||!this.i.textTracks.addEventListener)});
g.gS.prototype.Gx=g.ca(26,function(){return this.ra.Gx()});
g.RM.prototype.Fx=g.ca(25,function(){return!!this.i.textTracks});
g.gS.prototype.Fx=g.ca(24,function(){return this.ra.Fx()});
g.RM.prototype.Su=g.ca(23,function(a){this.ma();for(var b=0;b<a.length;b++)this.i.appendChild(a[b])});
g.gS.prototype.Su=g.ca(22,function(a){this.ra.Su(a)});
g.CM.prototype.kG=g.ca(21,function(){return!1});
g.CM.prototype.ao=g.ca(20,function(){});
g.DM.prototype.ao=g.ca(19,function(a,b,c){var d=this;this.isDisposed();b=this.Tp(a,b);this.Pm();this.i=g.Et(b,{format:"RAW",onSuccess:function(e){d.i=null;c(e.responseText,a)},
withCredentials:!0})});
g.FM.prototype.ao=g.ca(18,function(a,b,c){var d=this;this.isDisposed();b=this.Tp(a,b);this.Pm();this.i=g.Et(b,{format:"RAW",onSuccess:function(e){d.i=null;c(e.responseText,a)},
withCredentials:!0})});
g.QU.prototype.Vv=g.ca(6,function(){return this.K});
g.ZX.prototype.Vv=g.ca(5,function(){var a;return(null===(a=g.nM(this))||void 0===a?void 0:a.Js())||null});
g.eM.prototype.Js=g.ca(4,function(){return this.app.Vv()});
g.AX.prototype.Js=g.ca(3,function(){var a;return(null===(a=this.Ya)||void 0===a?void 0:a.Vv())||null});
var jUa={aa:"Afar",ab:"Abkhazian",ace:"Achinese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",ale:"Aleut",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",arp:"Arapaho",ars:"Najdi Arabic",arw:"Arawak",as:"Assamese",asa:"Asu",ast:"Asturian",av:"Avaric",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",
az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bas:"Basaa",bax:"Bamun",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bez:"Bena",bfd:"Bafut",bg:"Bulgarian",bh:"Bhojpuri",bho:"Bhojpuri",bi:"Bislama",bik:"Bikol",bin:"Bini",bkm:"Kom",bla:"Siksika",bm:"Bambara",bn:"Bangla",bo:"Tibetan",br:"Breton",bra:"Braj",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",
cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",chg:"Chagatai",chk:"Chuukese",chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",ckb_Arab:"Central Kurdish (Arabic)",co:"Corsican",cop:"Coptic",cr:"Cree",crh:"Crimean Turkish",cs:"Czech",csb:"Kashubian",cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",
de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",
es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fulah",ff_Adlm:"Fulah (Adlam)",ff_Latn:"Fulah (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",
gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",goh:"Old High German",gon:"Gondi",gor:"Gorontalo",got:"Gothic",grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hil:"Hiligaynon",hit:"Hittite",hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",
iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",ii:"Sichuan Yi",ik:"Inupiaq",ilo:"Iloko","in":"Indonesian",inh:"Ingush",io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kha:"Khasi",
kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",kj:"Kuanyama",kk:"Kazakh",kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",ku:"Kurdish",kum:"Kumyk",kut:"Kutenai",kv:"Komi",kw:"Cornish",ky:"Kyrgyz",la:"Latin",lad:"Ladino",lag:"Langi",lah:"Lahnda",lam:"Lamba",lb:"Luxembourgish",
lez:"Lezghian",lg:"Ganda",li:"Limburgish",lkt:"Lakota",ln:"Lingala",lo:"Lao",lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",man:"Mandingo",mas:"Masai",mde:"Maba",mdf:"Moksha",mdr:"Mandar",men:"Mende",mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",
mi:"M\u0101ori",mic:"Mi'kmaq",min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",my:"Burmese",mye:"Myene",myv:"Erzya",mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",
ne:"Nepali","new":"Newari",ng:"Ndonga",nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",nyn:"Nyankole",nyo:"Nyoro",nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",
pag:"Pangasinan",pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pon:"Pohnpeian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",raj:"Rajasthani",rap:"Rapanui",rar:"Rarotongan",rm:"Romansh",rn:"Rundi",ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",
sad:"Sandawe",sah:"Sakha",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",sel:"Selkup",ses:"Koyraboro Senni",sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",
sid:"Sidamo",sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",ssy:"Saho",st:"Southern Sotho",su:"Sundanese",su_Latn:"Sundanese (Latin)",suk:"Sukuma",sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",swc:"Congo Swahili",
syc:"Classical Syriac",syr:"Syriac",ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelau",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",tt:"Tatar",tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",
uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vi:"Vietnamese",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",xal:"Kalmyk",xh:"Xhosa",xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",
za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",zh:"Chinese",zh_Hans:"Chinese (Simplified)",zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"};E4.prototype.contains=function(a){a=g.pc(this.segments,a);return 0<=a||0>a&&1===(-a-1)%2};
E4.prototype.length=function(){return this.segments.length/2};
g.w(F4,g.H);g.k=F4.prototype;g.k.ya=function(){g.H.prototype.ya.call(this);this.B&&this.B.cancel()};
g.k.DA=function(){this.seekTo(this.player.getCurrentTime())};
g.k.seekTo=function(a){a-=this.player.kd();var b=this.i;this.i=g.Tb(this.Z.gm(a).i);b!==this.i&&this.X&&this.X()};
g.k.reset=function(){this.C=new E4;this.J=-1;this.B&&(this.B.cancel(),this.B=null)};
g.k.WL=function(){var a;this.isDisposed();var b;if(b=null!=this.i)b=this.i,b=b.i.Um(b);if(b&&!this.B&&!(this.i&&30<this.i.startTime-this.player.getCurrentTime())){b=this.i;b=b.i.Cu(b);if(this.Y.N("enable_h5_ssdai_caption")&&(null===(a=this.player.getVideoData())||void 0===a?0:a.enableServerStitchedDai)){var c=this.player.Js();if(c){var d=b.i[0].Oa,e=c.Mp(b.i[0].C,d,b.i[0].i.info.id,3);if(e)if(c=c.Jv(d),0===c)e&&(b.B=new g.wA(e));else if(2===c){this.K.start();hUa(this)&&this.seekTo(this.player.getCurrentTime());
return}}}b.i[0].duration?(this.C.contains(b.i[0].Oa)||iUa(this,b),this.i=g.Tb(b.i)):!this.Y.N("force_caption_seek_for_live_killswitch")&&hUa(this)&&this.seekTo(this.player.getCurrentTime())}this.K.start()};
g.k.ma=function(){};
g.w(G4,g.CM);g.k=G4.prototype;g.k.ao=function(a,b,c){var d=this;this.Pm();b=lUa(this,a.getId());b||(b=a.languageCode,b=this.i.isManifestless?mUa(this,b,"386"):mUa(this,b));if(b){var e=1E3*(b.index.getStartTimeInPeriod(b.index.getFirstSegmentNumber())-b.index.getStartTime(b.index.getFirstSegmentNumber())),f=new g.Fya(this.Y);this.B=new F4(f,this.I,b,function(h,l){c(h,a,l,e)},this.J||g.kC(b.info),function(){d.B&&d.B.reset();
d.D=!0})}};
g.k.kG=function(){var a=this.D;this.D=!1;return a};
g.k.Ys=function(a){var b=this.J?[new g.fF({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.fF({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:this.i.isManifestless?kUa(this,"386"):kUa(this);b=g.q(b);for(var c=b.next();!c.done;c=b.next())g.BM(this.u,c.value);a()};
g.k.Pm=function(){this.B&&(this.B.dispose(),this.B=null)};
g.k.Tp=function(){return""};
var U4=/^#(?:[0-9a-f]{3}){1,2}$/i,oUa=/#(.)(.)(.)/,nUa=/^#(?:[0-9a-f]{3}){1,2}$/i;var qUa=["left","right","center","justify"];g.w(I4,g.W);g.k=I4.prototype;g.k.CQ=function(a,b){var c=g.Rm(this.element,this.element.parentElement);this.Za=a-c.x;this.fb=b-c.y;g.M(this.element,"ytp-dragging")};
g.k.BQ=function(a,b){var c=g.Tm(this.element);a=a-this.Za-.02*this.playerWidth;var d=b-this.fb-.02*this.playerHeight,e=(a+c.width/2)/this.maxWidth*3;e=Math.floor(g.xg(e,0,2));var f=(d+c.height/2)/this.Sa*3;f=Math.floor(g.xg(f,0,2));b=e+3*f;a=(a+e/2*c.width)/this.maxWidth;a=100*g.xg(a,0,1);c=(d+f/2*c.height)/this.Sa;c=100*g.xg(c,0,1);this.u.params.wi=b;this.u.params.Xj=c;this.u.params.jh=a;this.i.wi=b;this.i.Xj=c;this.i.jh=a;this.Ja.wi=b;this.Ja.Xj=c;this.Ja.jh=a;this.UN()};
g.k.AQ=function(){g.tr(this.element,"ytp-dragging")};
g.k.UN=function(){this.Nt(this.D)};
g.k.getType=function(){return this.type};
g.k.Nt=function(a){var b=Math.min(this.LK(),this.maxWidth),c=this.KK(),d="";3===this.u.params.Mf&&(d="rotate(180deg)");g.Em(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.iD(a);a={transform:d,top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var e=.96*this.i.jh+2;d=this.i.wi;switch(d){case 0:case 3:case 6:(b=this.i.zd.fontSizeIncrement)&&0<b&&2!==this.i.Mf&&3!==
this.i.Mf&&(e=Math.max(e/(1+2*b),2));a.left=e+"%";break;case 1:case 4:case 7:a.left=e+"%";e=this.C.offsetWidth;b||e?(b=b||e+1,a.width=b+"px",a["margin-left"]=b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-e+"%"}b=.96*this.i.Xj+2;switch(d){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.Em(this.element,
a)};
g.k.iD=function(a){var b;for(b=0;b<a.length&&a[b]===this.D[b];b++);if(this.xa||this.D.length>b)b=0,this.xa=!1,this.D=[],this.J=this.Ba=this.Aa=null,g.jh(this.C);for(;b<a.length;b++)uUa(this,a[b])};
g.k.LK=function(){return 0};
g.k.KK=function(){return 0};
g.k.toString=function(){return g.W.prototype.toString.call(this)};g.w(J4,g.CM);J4.prototype.ao=function(a,b,c){fUa(this.videoData.videoId,a.vssId,c)};
J4.prototype.Ys=function(a){if(this.audioTrack)for(var b=g.q(this.audioTrack.captionTracks),c=b.next();!c.done;c=b.next())g.BM(this.u,c.value);a()};g.w(K4,I4);K4.prototype.iD=function(a){var b=this.u.i;I4.prototype.iD.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.i===e)var d=f;else{d={};Object.assign(d,c.i);Object.assign(d,oVa);var e=c.i;var f=d}uUa(this,c,d)}};
var oVa={jT:!0};g.w(L4,I4);g.k=L4.prototype;g.k.UN=function(){g.mr(this.Va)};
g.k.jW=function(){g.tr(this.element,"ytp-rollup-mode");this.Nt(this.Bb,!0)};
g.k.KK=function(){return this.B?this.X:this.S};
g.k.LK=function(){return this.B?this.S:this.X};
g.k.Nt=function(a,b){this.Bb=a;if(this.u.params.Im){for(var c=0,d=0;d<this.D.length&&c<a.length;d++)this.D[d]===a[c]&&c++;0<c&&c<a.length&&(a=this.D.concat(a.slice(c)));this.kb=this.X;this.S=this.X=0;I4.prototype.Nt.call(this,a);xUa(this,b)}I4.prototype.Nt.call(this,a)};g.w(M4,g.Ny);M4.prototype.toString=function(){return g.Ny.prototype.toString.call(this)};g.w(N4,g.Ny);N4.prototype.toString=function(){return g.Ny.prototype.toString.call(this)};
var O4=0;g.w(P4,g.H);P4.prototype.u=function(){return[]};
P4.prototype.reset=function(){};g.w(Q4,P4);Q4.prototype.reset=function(){this.K={};this.B=this.i=null;this.J=!0};
Q4.prototype.u=function(a,b){a=a.firstChild;a.getAttribute("format");b=b||0;Number.isFinite(b);a=Array.from(a.childNodes);a=g.q(a);for(var c=a.next();!c.done;c=a.next())if(c=c.value,1===c.nodeType)switch(c.tagName){case "head":var d=c;break;case "body":var e=c}if(d)for(d=Array.from(d.childNodes),d=g.q(d),a=d.next();!a.done;a=d.next())if(a=a.value,1===a.nodeType)switch(a.tagName){case "pen":c=a.getAttribute("id");var f=this.pens,h={},l=a.getAttribute("p");l&&Object.assign(h,this.pens[l]);l=S4(a,"b");
null!=l&&(h.bold=l);l=S4(a,"i");null!=l&&(h.Fj=l);l=S4(a,"u");null!=l&&(h.underline=l);l=T4(a,"et");null!=l&&(h.charEdgeStyle=l);l=T4(a,"of");null!=l&&(h.offset=l);l=V4(a,"bc");null!=l&&(h.background=l);l=V4(a,"ec");null!=l&&(h.xD=l);l=V4(a,"fc");null!=l&&(h.color=l);l=T4(a,"fs");null!=l&&0!==l&&(h.fontFamily=l);l=R4(a,"sz");void 0!==l&&(h.fontSizeIncrement=l/100-1);l=R4(a,"bo");void 0!==l&&(h.backgroundOpacity=l/255);l=R4(a,"fo");void 0!==l&&(h.textOpacity=l/255);l=T4(a,"rb");null!=l&&10!==l&&0!==
l&&(h.pe=10<l?l-1:l);a=T4(a,"hg");null!=a&&(h.nL=a);f[c]=h;break;case "ws":c=a.getAttribute("id");this.X[c]=BUa(this,a);break;case "wp":c=a.getAttribute("id"),this.S[c]=CUa(this,a)}if(e){d=[];e=Array.from(e.childNodes);e=g.q(e);for(a=e.next();!a.done;a=e.next())if(a=a.value,1===a.nodeType)switch(a.tagName){case "w":this.i=DUa(this,a,b,!1);(a=this.K[this.i.id])&&a.end>this.i.start&&(a.end=this.i.start);this.K[this.i.id]=this.i;d.push(this.i);break;case "p":l=b;c=[];f=a.getAttribute("w")||this.D;h=
!!S4(a,"a");l=(R4(a,"t")||0)+l;var m=R4(a,"d")||5E3;h||(!this.J&&this.B&&this.B.windowId===f&&this.B.end>l&&(this.B.end=l),this.B&&"\n"===this.B.text&&(this.B.text=""));var n=h?6:5,p=a.getAttribute("p");p=p?this.pens[p]:null;var r=Array.from(a.childNodes);r.length&&(this.J=null!=a.getAttribute("d"));for(var t=0;t<r.length;t++){var v=r[t],x=void 0;0<t&&(h=!0);var y=void 0;1===v.nodeType&&(y=v);if(y&&"s"===y.tagName){if((v=(v=y.getAttribute("p"))?this.pens[v]:null)&&v.pe&&(1===v.pe?(v=r.slice(t,t+4),
4===v.length&&(x=AUa(l,m,f,h,n,v,this.pens),t+=3)):x=AUa(l,m,f,h,n,[y],this.pens)),!x){var z=y;x=l;y=m;v=f;var D=h,G=n,F=z.textContent?z.textContent:"",J=z.getAttribute("p");J=J?this.pens[J]:null;z=R4(z,"t")||0;x=new M4(x+z,y-z,G,v,F,D,J)}}else x=new M4(l,m,n,f,v.textContent||"",h,p);c.push(x);this.B=x}if(0<c.length)for(c[0].windowId===this.D&&(this.i=DUa(this,a,b,!0),d.push(this.i)),a=g.q(c),c=a.next();!c.done;c=a.next())c=c.value,c.windowId=this.i.id,this.i.i.push(c),d.push(c)}b=d}else b=[];return b};var pVa=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.w(W4,P4);W4.prototype.reset=function(){this.B.clear()};
W4.prototype.u=function(a,b){var c=JSON.parse(a);if(!c)return[];if(c.pens){a=0;for(var d=g.q(c.pens),e=d.next();!e.done;e=d.next()){e=e.value;var f={},h=e.pParentId;h&&Object.assign(f,this.i.get(h));e.bAttr&&(f.bold=!0);e.iAttr&&(f.Fj=!0);e.uAttr&&(f.underline=!0);h=e.ofOffset;null!=h&&(f.offset=h);void 0!==e.szPenSize&&(f.fontSizeIncrement=e.szPenSize/100-1);h=e.etEdgeType;null!=h&&(f.charEdgeStyle=h);void 0!==e.ecEdgeColor&&(f.xD=X4(e.ecEdgeColor));h=e.fsFontStyle;null!=h&&0!==h&&(f.fontFamily=
h);void 0!==e.fcForeColor&&(f.color=X4(e.fcForeColor));void 0!==e.foForeAlpha&&(f.textOpacity=e.foForeAlpha/255);void 0!==e.bcBackColor&&(f.background=X4(e.bcBackColor));void 0!==e.boBackAlpha&&(f.backgroundOpacity=e.boBackAlpha/255);(h=e.rbRuby)&&10!==h&&(f.pe=10<h?h-1:h,f.Wj=pVa.get(f.pe));e.hgHorizGroup&&(f.nL=e.hgHorizGroup);this.i.set(a++,f)}}if(c.wsWinStyles)for(a=0,d=g.q(c.wsWinStyles),e=d.next();!e.done;e=d.next())e=e.value,f={},(h=e.wsParentId)?Object.assign(f,this.D.get(h)):Object.assign(f,
this.J),void 0!==e.mhModeHint&&(f.kt=e.mhModeHint),void 0!==e.juJustifCode&&(f.textAlign=e.juJustifCode),void 0!==e.pdPrintDir&&(f.Mf=e.pdPrintDir),void 0!==e.sdScrollDir&&(f.dH=e.sdScrollDir),void 0!==e.wfcWinFillColor&&(f.windowColor=X4(e.wfcWinFillColor)),void 0!==e.wfoWinFillAlpha&&(f.windowOpacity=e.wfoWinFillAlpha/255),this.D.set(a++,f);if(c.wpWinPositions)for(a=0,d=g.q(c.wpWinPositions),e=d.next();!e.done;e=d.next())e=e.value,f={},(h=e.wpParentId)&&Object.assign(f,this.C.get(h)),void 0!==e.ahHorPos&&
(f.jh=e.ahHorPos),void 0!==e.apPoint&&(f.wi=e.apPoint),void 0!==e.avVerPos&&(f.Xj=e.avVerPos),void 0!==e.ccCols&&(f.qn=e.ccCols),void 0!==e.rcRows&&(f.Im=e.rcRows),this.C.set(a++,f);if(c.events){a=[];c=g.q(c.events);for(d=c.next();!d.done;d=c.next()){var l=d.value;d=(l.tStartMs||0)+b;e=l.dDurationMs||0;if(l.id)f=String(l.id),d=EUa(this,l,d,e,f),a.push(d),this.B.set(f,d);else{l.wWinId?f=l.wWinId.toString():(f="_"+O4++,h=EUa(this,l,d,e,f),a.push(h),this.B.set(f,h));0===e&&(e=5E3);h=this.B.get(f);var m=
!!l.aAppend,n=m?6:5,p=l.segs,r=null;l.pPenId&&(r=this.i.get(l.pPenId));for(l=0;l<p.length;l++){var t=p[l],v=t.utf8;if(v){var x=t.tOffsetMs||0,y=null;t.pPenId&&(y=this.i.get(t.pPenId));if(2===(null!=h.params.kt?h.params.kt:1<h.i.length?1:0)&&m&&"\n"===v)continue;if(t=y&&1===y.pe)if(t=l,t+3>=p.length||!p[t+1].pPenId||!p[t+2].pPenId||!p[t+3].pPenId)t=!1;else{var z=p[t+1].pPenId;(z=this.i.get(z))&&z.pe&&2===z.pe?(z=p[t+2].pPenId,z=this.i.get(z),!z||!z.pe||3>z.pe?t=!1:(z=p[t+3].pPenId,t=(z=this.i.get(z))&&
z.pe&&2===z.pe?!0:!1)):t=!1}if(t){x=p[l+1].utf8;t=p[l+3].utf8;z=p[l+2].utf8;var D=this.i.get(p[l+2].pPenId);v=zUa(v,x,z,t,D);m=new M4(d,e,n,f,v,m,y);l+=3}else m=new M4(d+x,e-x,n,h.id,v,m,y||r);m&&(a.push(m),h.i.push(m))}m=!0}}}b=a}else b=[];return b};Z4.prototype.clear=function(){this.B=this.time=this.mode=0;this.i=[];this.reset()};
Z4.prototype.reset=function(){this.mode=0;this.C.reset(0);this.D.reset(1)};
var FUa=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];$4.prototype.set=function(a){this.type=a};
$4.prototype.get=function(){return this.type};
a5.prototype.clear=function(){this.state=0};
a5.prototype.update=function(){this.state=2===this.state?1:0};
a5.prototype.isValid=function(){return 0!==this.state};
a5.prototype.matches=function(a,b){return this.isValid()&&a===this.vp&&b===this.fn};
KUa.prototype.reset=function(){this.timestamp=this.i=0};
b5.prototype.updateTime=function(a){for(var b=1;15>=b;++b)for(var c=1;32>=c;++c)this.B[b][c].timestamp=a};
b5.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.B[b][c];a=0===d.i?a+"_":a+String.fromCharCode(d.i)}a+="\n"}return a};
b5.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.B[b][c].reset();this.C=a;this.i=0;this.u=this.row=1};
var LUa=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],MUa=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],NUa=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],OUa=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];h5.prototype.reset=function(a,b){this.D=b;this.style.set(2);this.u=this.J;this.C=this.K;this.i=this.u;var c=(a<<2)+(b<<1);this.J.reset(c);this.K.reset(c);this.text.reset((a<<2)+(b<<1)+1)};
Y4.prototype.reset=function(a){this.D=a;this.u.clear();this.C=this.B;this.B.reset(a,0);this.J.reset(a,1)};TUa.prototype.D=function(){};g.w(j5,TUa);j5.prototype.D=function(a,b,c,d,e){if(c<d){var f="_"+O4++;c=c/1E3-this.K;d=d/1E3-this.K;a=new N4(c,d-c,5,f,{textAlign:0,wi:0,jh:2.5*b,Xj:5.33*a});e=new M4(c,d-c,5,f,e);this.B.push(a);this.B.push(e)}};
g.w(m5,P4);m5.prototype.u=function(a){a=new j5(a,a.byteLength,this.B);if(UUa(a)){for(;a.i<a.u.byteLength;)for(0===a.version?a.C=l5(a)*(1E3/45):1===a.version&&(a.C=4294967296*l5(a)+l5(a)),a.J=k5(a);0<a.J;a.J--){var b=k5(a),c=k5(a),d=k5(a);b&4&&(b&3)===this.track&&(0===this.track||1===this.track)&&(b=this.i,b.i.push({time:a.C,type:this.track,OJ:c,PJ:d,order:b.i.length}))}JUa(this.i,a);return a.B}return[]};
m5.prototype.reset=function(){this.i.clear()};g.w(o5,P4);
o5.prototype.u=function(a,b){var c=[];a=a.split(qVa);for(var d=1;d<a.length;d++){var e=a[d],f=b;if(""!==e&&!rVa.test(e)){var h=E5.exec(e);if(h&&4<=h.length){var l=p5(h[1]),m=p5(h[2])-l;l+=f;var n=(h=h[3])?h.split(" "):[];h={};var p=null;var r="";var t=null,v="";n=g.q(n);for(var x=n.next();!x.done;x=n.next())if(x=x.value.split(":"),2===x.length){var y=x[1];switch(x[0]){case "line":x=y.split(",");x[0].endsWith("%")&&(p=x[0],h.Xj=Number.parseInt(p,10),2===x.length&&(r=x[1].trim()));break;case "position":x=
y.split(",");t=x[0];h.jh=Number.parseInt(t,10);2===x.length&&(v=x[1].trim());break;case "align":switch(y){case "start":h.textAlign=0;break;case "middle":h.textAlign=2;break;case "end":h.textAlign=1}}}p||r||(r="end");if(!t)switch(h.textAlign){case 0:h.jh=0;break;case 1:h.jh=100;break;case 2:h.jh=50}if(null!=h.textAlign){p=0;switch(r){case "center":p+=3;break;case "end":p+=6;break;default:p+=0}switch(v){case "line-left":p+=0;break;case "center":p+=1;break;case "line-right":p+=2;break;default:switch(h.textAlign){case 0:p+=
0;break;case 2:p+=1;break;case 1:p+=2}}r=0>p||8<p?7:p;h.wi=r}e=e.substring(E5.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");v=h;h=e;e={};if(0>h.indexOf("<")&&0>h.indexOf("&"))f=WUa(l,m,5,v),m=new M4(l,m,5,f.id,h,!1,g.We(e)?void 0:e),c.push(f),c.push(m),f.i.push(m);else for(r=h.split(sVa),1===r.length?(h=5,v=WUa(l,m,h,v)):(p=h=6,v=Object.assign({qn:32},v),v=new N4(l,m,p,"_"+O4++,v)),c.push(v),p=l,t=0;t<r.length;t++)n=r[t],0===t%2?(x=g.Y1("<html>"+n+"</html>"),x.getElementsByTagName("parsererror").length?
(y=x.createElement("span"),y.appendChild(x.createTextNode(n))):y=x.firstChild,VUa(this,p,m-(p-l),h,v,0<t,y,e,c)):p=p5(n)+f}E5.lastIndex=0}}return c};
var rVa=/^NOTE/,qVa=/(?:\r\n|\r|\n){2,}/,E5=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),sVa=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");g.nS.Tz(o5,{u:"wvppt"});g.w(q5,g.H);q5.prototype.clear=function(){this.i&&this.i.dispose();this.i=null};
q5.prototype.reset=function(){this.i&&this.i.reset()};
q5.prototype.ya=function(){g.H.prototype.ya.call(this);this.clear()};var C5={windowColor:"#080808",windowOpacity:0,textAlign:2,wi:7,jh:50,Xj:100,zd:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.w(t5,g.zM);g.k=t5.prototype;g.k.ya=function(){if(this.B||this.X){var a=this.I.qd();a&&!a.isDisposed()&&a.Zr()}else D5(this,!1);g.zM.prototype.ya.call(this)};
g.k.Kq=function(){if(this.La)return this.B||this.X;var a=C4(this.player.getAudioTrack(),D4(this.Y));return"CAPTIONS_INITIAL_STATE_ON_REQUIRED"===a?!0:"CAPTIONS_INITIAL_STATE_OFF_REQUIRED"===a?v5(this):u5(this)||v5(this)?!0:hVa(this)};
g.k.load=function(){var a=this;g.zM.prototype.load.call(this);var b=!this.Y.N("web_player_captions_track_list_changed_killswitch");this.J=this.player.getAudioTrack();this.u?(this.i&&(this.Va.clear(),this.B?kVa(this,!0):3!==this.player.getPresentingPlayerType()&&this.u.ao(this.i,"json3",function(c,d,e,f){c&&(a.u.kG()&&(a.xa=[],a.I.cf("captions"),g.kr(a.Aa),a.Va.reset()),c=bVa(a.Va,c,d,e,f),a.Y.N("tv_caption_performance_optimization")?a.player.Gd(c,void 0,a.Xa):a.player.Gd(c),!a.Z||a.X||y5(a)||g.sE(a.Y)||
g.lE(a.Y)||(g.nr(a.Ba),c=yUa({wi:0,jh:5,Xj:5,Im:2,textAlign:0,Mf:0,lang:"en"}),a.Ja=[c],d=["Click "," for settings"],a.Za||(e=new g.dK(g.tK()),g.I(a,e),a.Za=e.element),e=c.end-c.start,(f=g.gF(a.i))&&a.Ja.push(new M4(c.start,e,0,c.id,f)),a.Ja.push(new M4(c.start,e,0,c.id,d[0]),new M4(c.start,e,0,c.id,a.Za,!0),new M4(c.start,e,0,c.id,d[1],!0)),a.player.Gd(a.Ja),g.lr(a.Ba)),!a.Z||a.X||y5(a)||(g.FE(a.Y)?A5(a,!0):B5(a,"module-enabled",!0),a.J&&(a.J.C=a.i),a.player.Sq()),a.Z=!1)}),!b||this.B||this.X||y5(this)||
this.player.Pa("captionschanged",g.hF(this.i))),b||(this.i&&!y5(this)?this.player.Pa("captionschanged",g.hF(this.i)):this.player.Pa("onCaptionsTrackListChanged"))):(this.u=iVa(this),g.I(this,this.u),this.u.Ys(function(){jVa(a)}))};
g.k.unload=function(){this.B&&this.i?kVa(this,!1):(this.Ba&&g.nr(this.Ba),this.player.cf("captions"),this.xa=[],this.u&&this.u.Pm(),this.Va.clear(),this.K&&this.player.Gd(this.K),this.wH());g.zM.prototype.unload.call(this);this.player.Sq();this.player.Pa("captionschanged",{})};
g.k.create=function(){this.Kq()&&this.load()};
g.k.TW=function(){for(var a=this.I.qd().Ee().textTracks,b=null,c=0;c<a.length;c++)if("showing"===a[c].mode)a:{b=a[c].id;var d=g.AM(this.u.u,!0);for(var e=0;e<d.length;e++)if(d[e].toString()===b){b=d[e];break a}b=null}(this.loaded?this.i:null)!==b&&z5(this,b,!0)};
g.k.AY=function(){!this.i&&this.B||this.unload()};
g.k.onCueRangeEnter=function(a){this.xa.push(a);g.kr(this.Aa)};
g.k.onCueRangeExit=function(a){g.dc(this.xa,a);this.u instanceof G4&&this.u.J&&this.player.Kf([a]);g.kr(this.Aa)};
g.k.vX=function(a){if(a instanceof N4){var b=this.S[a.id];b&&b.u!==a&&(b.dispose(),delete this.S[a.id],b=null);b||(b=mVa(this,a))&&(this.S[a.id]=b)}else b=a.windowId,this.Ka[b]||(this.Ka[b]=[]),this.Ka[b].push(a)};
g.k.getCaptionWindowContainerId=function(){return this.Sa.element.id};
g.k.BX=function(){nVa(this,this.Ja);this.Ja=null};
g.k.uH=function(){var a=this;if(!this.kb||!this.B){this.Aa.stop();g.Xe(this.Ka);this.xa.sort(g.Oy);var b=this.xa;if(this.K){var c=g.Cp(b,function(d){return-1===this.K.indexOf(d)},this);
c.length&&(b=c)}g.uc(b,this.vX,this);g.He(this.S,function(d,e){a.Ka[e]?(d.element.parentNode||(d instanceof L4||d instanceof K4||g.Ke(a.S,function(f,h){h!==e&&f.u.params.wi===d.u.params.wi&&f.u.params.jh===d.u.params.jh&&f.u.params.Xj===d.u.params.Xj&&(f.dispose(),delete a.S[h]);return h===e},a),lVa(a,d.element)),d.Nt(a.Ka[e])):(d.dispose(),delete a.S[e])},this)}};
g.k.GX=function(){r5(this,{},!0);this.Y.N("web_player_disable_publish_captions_settings_changed_on_reset")||this.player.Pa("captionssettingschanged")};
g.k.ES=function(){var a=C5.zd;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.Fj?3:a.bold?1:a.Fj?2:0,textOpacity:a.textOpacity,windowColor:C5.windowColor,windowOpacity:C5.windowOpacity};var b=s5(this)||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&(a.backgroundOpacity=
b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&(a.fontSizeIncrement=
b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);null!=b.windowOpacity&&
(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.k.UO=function(a,b){var c={};Object.assign(c,s5(this));Object.assign(c,a);r5(this,c,b);this.player.Pa("captionssettingschanged")};
g.k.wH=function(){!this.B&&this.loaded&&(g.He(this.S,function(a,b){a.dispose();delete this.S[b]},this),this.uH())};
g.k.sf=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.xg(b,-2,4);this.UO({fontSizeIncrement:c});return c;case "reload":b&&!this.B&&z5(this,this.i,!0);break;case "stickyLoading":void 0!==b&&this.Y.B&&(g.FE(this.Y)?A5(this,!!b):B5(this,"module-enabled",!!b));break;case "track":if(!this.u)return{};if(b){if(this.B)break;if(!g.Na(b))break;if(g.We(b)){z5(this,null,!0);break}a=g.AM(this.u.u,!0);for(var d=0;d<a.length;d++){var e=a[d];e.languageCode!==b.languageCode||c&&e.languageName!==
b.languageName||(c=b.translationLanguage?eUa(e,b.translationLanguage):e)}!c||c===this.i&&this.loaded||(b=g.sqa(),a=g.iF(c),b.length&&a===b[b.length-1]||(b.push(a),g.ky("yt-player-caption-language-preferences",b)),z5(this,c,!0))}else return this.loaded&&this.i&&!y5(this)?g.hF(this.i):{};return"";case "tracklist":return this.u?g.on(g.AM(this.u.u,!(!b||!b.includeAsr)),function(f){return g.hF(f)}):[];
case "translationLanguages":return this.u?this.u.C.map(function(f){return Object.assign({},f)}):[];
case "sampleSubtitles":this.B||void 0===b||D5(this,!!b);break;case "sampleSubtitlesCustomized":this.B||D5(this,!!b,b)}};
g.k.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.Y.B&&a.push("stickyLoading");return a};
g.k.uE=function(){var a=this.i;if(a){var b=a.vssId;a.translationLanguage&&b&&!this.Y.N("auto_translation_logging_killswitch")&&(b="t"+b+"."+g.iF(a));return{cc:b}}return{}};
g.k.pY=function(){this.loaded&&this.i&&!y5(this)?(g.FE(this.Y)?A5(this,!1):B5(this,"module-enabled",!1),this.unload(),v5(this,!0)&&z5(this,w5(this),!1)):this.CO()};
g.k.CO=function(){this.loaded&&this.i&&!y5(this)||z5(this,y5(this)||!this.i?x5(this,!0):this.i,!0)};
g.k.BU=function(){var a=y5(this);v5(this,a)?z5(this,this.player.getAudioTrack().i,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.Kq()&&(a?z5(this,x5(this),!1):this.load()))};
g.k.rV=function(){var a=this.I.qd();a&&!a.isDisposed()&&a.Zr();this.I.isFullscreen()?(this.B=this.La=!0,this.loaded&&jVa(this)):(this.La="3"===this.Y.controlsType,this.B=eVa(this));z5(this,this.i)};
g.nS.Tz(t5,{uH:"smucd"});g.yM("captions",t5);})(_yt_player);
